### ISSUE TITLE
请问这里面存在了几个队列？

### ISSUE THREAD

**Issue by a-mochis** [fnpac/KMQueue#1]
KMQueueManager里面的queueMap是备份队列还是生产者队列？

**Comment by Trekkiii** [comment]
```
new KMQueueManager.Builder("127.0.0.1", 6379, "worker1_queue", "worker2_queue:safe")
```
通过上述方式，会创建三个队列，queueMap会保存这三个队列：

- 任务队列（2个）：`worker1_queue`，`worker2_queue`
- 备份队列（1个，worker2_queue指定了`safe`模式，会为该队列创建备份队列）

**Comment by a-mochis** [comment]
好的了解，也就是说queueMap会存储这三个队列，那么比如说我要访问worker1_queue或者worker2_queue都是在这一个队列里就可以完成吗？如果是的话，是使用的什么方法呢？
请问能加一下您的联系方式吗？有问题能够解惑

**Comment by Trekkiii** [comment]
不太理解你的意思，我的qq：631521383
